# Generated by Django 4.2.7 on 2024-01-15 16:28

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('decky', '0002_alter_kategori_options_kategori_banner_satu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Data Kategori'},
        ),
        migrations.AlterModelOptions(
            name='kontak',
            options={'verbose_name_plural': 'Data Kontak'},
        ),
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name_plural': 'Data Produk'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Data Profil'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name_plural': 'Data Slide'},
        ),
        migrations.AlterModelOptions(
            name='statis',
            options={'verbose_name_plural': 'Data Statis'},
        ),
        migrations.RemoveField(
            model_name='produk',
            name='aktif',
        ),
        migrations.AlterField(
            model_name='kategori',
            name='banner_dua',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[575, 200], upload_to='gambar/banner', verbose_name='Gambar 1 (575 x 200 pixel)'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='banner_satu',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[575, 200], upload_to='gambar/banner', verbose_name='Gambar 1 (575 x 200 pixel)'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kontak',
            name='no_whatsup',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='diskon',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Diskon %'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/product', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_dua',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/product', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_empat',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/product', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_lima',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/product', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_satu',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/product', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_tiga',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/product', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='no_whatsup',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='gambar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1200], upload_to='gambar/profil', verbose_name='Gambar (1920 x 1200 pixel)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='gambar_slide',
            field=models.ImageField(null=True, upload_to='gambar/slide', verbose_name='Gambar Slide (475 x 880 pixel)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='teks_awal',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='teks_dua',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='teks_tiga',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
